# Generated by Django 4.0 on 2022-01-10 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_remove_seller_seller_delete_customer'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0003_alter_product_image_alter_product_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
