# Generated by Django 4.0 on 2022-01-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_seller_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
