# Generated by Django 4.0 on 2022-01-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/404_not_found.png', upload_to='images/'),
        ),
    ]
